# Generated by Django 5.2.4 on 2025-10-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_discount_alter_product_price_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
            ],
            options={
                'verbose_name': 'Wishlist',
                'verbose_name_plural': 'Wishlist',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.wishlistitem',),
        ),
    ]
